In [1]:
list1=[1, 2, 3, 4, 5]
print(type(list1))

<class 'list'>


In [2]:
type(list1)

list

In [3]:
len(list1)

5

In [4]:
list2=[2,3,4,5,6,7]

In [5]:
print(list2)

[2, 3, 4, 5, 6, 7]


In [6]:
len(list2)

6

In [8]:
def find_value_in_tuple(val, tup):
    try:
        tup.index(val)
        return tup.index(val)
    except Exception:
        return "sorry val is not in tuple"
    
    find_value_in_tuple(2, tuple1)

In [9]:
tuple1 = (1, 2, 6, 8)


In [10]:
  find_value_in_tuple(2, tuple1)

1

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
df_Country = pd.read_csv("Country_data.csv")
df_Country.head(10)

Entity  indiv_libs_vdem_owid  electdem_vdem_owid  libdem_vdem_owid  \
0  Afghanistan                 0.266               0.160             0.104   
1      Albania                 0.006               0.173             0.055   
2      Algeria                 0.428               0.084             0.065   
3       Angola                 0.024               0.010             0.035   
4    Argentina                 0.354               0.105             0.086   
5      Armenia                 0.094               0.102             0.024   
6    Australia                 0.980               0.860             0.807   
7      Austria                 0.949               0.843             0.728   
8   Azerbaijan                 0.094               0.102             0.024   
9      Bahrain                 0.449               0.024               NaN   

    Countries  Economic.Freedom.Summary.Index  Government.consumption  \
0         NaN                        5.506573                6.393604   
1     Albania                        3.713222                3.170575   
2     Algeria                        4.680000                5.540000   
3      Angola                        4.547754                6.109553   
4   Argentina                        5.980000                7.930000   
5     Armenia                        4.543790                6.061647   
6   Australia                        7.560000                6.170000   
7     Austria                        6.610000                5.450000   
8  Azerbaijan                        4.562497                6.062738   
9     Bahrain                        5.990742                7.066136   

   Transfers.and.subsidies  Government.investment  State.ownership.of.assets  \
0                 8.740967               5.519734                   5.025106   
1                 8.262926              -0.627520                   0.180000   
2                 9.322154               7.320000                   2.490000   
3                 8.385527               4.949296                   3.180000   
4                 8.006018               8.187808                   6.150000   
5                 9.695219               2.974573                   3.267026   
6                 6.968283              10.000000                   7.380000   
7                 6.070000               7.820000                   4.780000   
8                 9.676493               3.009096                   3.295890   
9                 9.231391               7.644778                   2.550000   

   ...  Centralized.collective.bargaining  Hours.Regulations  Conscription  \
0  ...                           5.897546           5.932564      2.392234   
1  ...                           4.220652           4.846848      0.000000   
2  ...                           5.540452           6.185718      3.000000   
3  ...                           4.641346           5.671838      0.536243   
4  ...                           5.180000           5.720000      0.000000   
5  ...                           6.120053           5.976917      3.102853   
6  ...                           5.180000           5.321900      0.000000   
7  ...                           4.490000           5.010000      0.000000   
8  ...                           6.118530           5.973363      3.112880   
9  ...                           6.308791           6.602108     -1.105166   

   Labor.market.regulations  Impartial.Public.Administration  Regulation  \
0                  4.700103                         4.887146    4.776903   
1                  4.215714                         1.750000    3.230021   
2                  4.572435                         3.910000    3.630000   
3                  3.955813                         2.370000    3.778725   
4                  3.630000                         2.420000    5.310000   
5                  5.022989                         3.191819    4.010850   
6                  4.346862                         9.760000    5.720000 

In [30]:
df_Country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 43 columns):
 #   Column                                                Non-Null Count  Dtype  
---  ------                                                --------------  -----  
 0   Entity                                                182 non-null    object 
 1   indiv_libs_vdem_owid                                  177 non-null    float64
 2   electdem_vdem_owid                                    177 non-null    float64
 3   libdem_vdem_owid                                      175 non-null    float64
 4   Countries                                             165 non-null    object 
 5   Economic.Freedom.Summary.Index                        182 non-null    float64
 6   Government.consumption                                182 non-null    float64
 7   Transfers.and.subsidies                               182 non-null    float64
 8   Government.investment                                 182 no

In [31]:
df_Country.describe()

indiv_libs_vdem_owid  electdem_vdem_owid  libdem_vdem_owid  \
count            177.000000          177.000000        175.000000   
mean               0.433633            0.271169          0.205794   
std                0.308818            0.255504          0.239538   
min                0.003000            0.010000          0.011000   
25%                0.135000            0.102000          0.044500   
50%                0.373000            0.169000          0.096000   
75%                0.682000            0.322000          0.244000   
max                0.992000            0.905000          0.879000   

       Economic.Freedom.Summary.Index  Government.consumption  \
count                      182.000000              182.000000   
mean                         5.497105                6.397742   
std                          0.990792                1.631789   
min                          3.400000                0.050000   
25%                          4.824416                5.624896   
50%                          5.483484                6.393604   
75%                          6.147837                7.437500   
max                          8.420000               11.037714   

       Transfers.and.subsidies  Government.investment  \
count               182.000000             182.000000   
mean                  8.750740               5.512288   
std                   1.168317               2.535629   
min                   4.480000              -0.940513   
25%                   8.386646               4.052806   
50%                   8.949077               5.519734   
75%                   9.596289               7.411258   
max                  10.924050              10.000000   

       State.ownership.of.assets  Size.of.Government  Judicial.independence  \
count                 182.000000          182.000000             182.000000   
mean                    5.014970            6.040210               5.093428   
std                     1.902797            1.388335               1.520615   
min                     0.130000            2.020000               2.250000   
25%                     4.065000            5.135000               4.080000   
50%                     5.025106            6.041385               5.031735   
75%                     6.277500            7.107500               5.805000   
max                     9.310000            9.360000               8.540000   

       ...  Interest.rate.controls.negative.real.interest.rates.  \
count  ...                                         182.000000      
mean   ...                                           7.431721      
std    ...                                           1.337461      
min    ...                                           1.372522      
25%    ...                                           7.017368      
50%    ...                                           7.439856      
75%    ...                                           8.000000      
max    ...                                          10.404420      

       Credit.market.regulations  Centralized.collective.bargaining  \
count                 182.000000                         182.000000   
mean                    5.299373                           5.899200   
std                     2.879924                           0.977878   
min                    -1.128499                           3.652118   
25%                     3.440618                           5.180000   
50%                     5.316401                           5.897546   
75%                     7.685331                           6.305401   
max                    10.000000                           8.187470   

       Hours.Regulations  Conscription  Labor.market.regulations  \
count         182.000000    182.000000                182.000000   
mean            5.938018      2.390425                  4.702679   
std             0.660809      3.361388                  0.964482   
min             2.730000     -6.698552          

In [32]:
df_Country.shape

(182, 43)

In [33]:
df_Country.shape[0]

182

In [34]:
df_Country.columns

Index(['Entity', 'indiv_libs_vdem_owid', 'electdem_vdem_owid',
       'libdem_vdem_owid', 'Countries', 'Economic.Freedom.Summary.Index',
       'Government.consumption', 'Transfers.and.subsidies',
       'Government.investment', 'State.ownership.of.assets',
       'Size.of.Government', 'Judicial.independence', 'Impartial.courts',
       'Integrity.of.the.legal.system', 'Legal.enforcement.of.contracts',
       'Gender.Legal.Rights.Adjustment', 'Legal.System...Property.Rights',
       'Money.growth', 'Standard.deviation.of.inflation',
       'Inflation..Most.recent.year',
       'Freedom.to.own.foreign.currency.bank.accounts', 'Sound.Money',
       'Revenue.from.trade.taxes....of.trade.sector.', 'Tariffs',
       'Black.market.exchange.rates', 'Financial.Openness', 'Capital.controls',
       'Controls.of.the.movement.of.capital.and.people',
       'Freedom.to.trade.Internationally', 'Ownership.of.banks',
       'Private.sector.credit',
       'Interest.rate.controls.negative.real.interes

In [35]:
df_Country.dtypes

Entity                                                   object
indiv_libs_vdem_owid                                    float64
electdem_vdem_owid                                      float64
libdem_vdem_owid                                        float64
Countries                                                object
Economic.Freedom.Summary.Index                          float64
Government.consumption                                  float64
Transfers.and.subsidies                                 float64
Government.investment                                   float64
State.ownership.of.assets                               float64
Size.of.Government                                      float64
Judicial.independence                                   float64
Impartial.courts                                        float64
Integrity.of.the.legal.system                           float64
Legal.enforcement.of.contracts                          float64
Gender.Legal.Rights.Adjustment          

In [37]:
df_Country.groupby('Regime_type')


In [38]:
df_grouped=df_Country.groupby('Regime_type')

In [39]:
df_grouped.describe()

indiv_libs_vdem_owid                      \
                                              count      mean       std   
Regime_type                                                               
Democracy                                      39.0  0.841462  0.204599   
Military rule                                  34.0  0.272853  0.142028   
Monarchy                                       13.0  0.357462  0.190659   
Multi-party authoritarian rule                  6.0  0.609000  0.210711   
Other oligarchy                                 4.0  0.218250  0.216649   
Personalist rule                               20.0  0.390350  0.227198   
Single-party rule                              40.0  0.264850  0.209088   
unknown                                        21.0  0.337333  0.305038   

                                                                       \
                                  min     25%     50%      75%    max   
Regime_type                                                             
Democracy                       0.049  0.7910  0.9090  0.97250  0.992   
Military rule                   0.078  0.1435  0.2440  0.37300  0.592   
Monarchy                        0.118  0.2020  0.3800  0.40200  0.726   
Multi-party authoritarian rule  0.336  0.4780  0.5795  0.78150  0.866   
Other oligarchy                 0.099  0.1095  0.1155  0.22425  0.543   
Personalist rule                0.003  0.2530  0.4000  0.54700  0.769   
Single-party rule               0.006  0.0940  0.2080  0.36625  0.686   
unknown                         0.012  0.0940  0.1710  0.57100  0.926   

                               electdem_vdem_owid            ...  \
                                            count      mean  ...   
Regime_type                                                  ...   
Democracy                                    39.0  0.697615  ...   
Military rule                                34.0  0.132794  ...   
Monarchy                                     13.0  0.122000  ...   
Multi-party authoritarian rule                6.0  0.270333  ...   
Other oligarchy                               4.0  0.151500  ...   
Personalist rule                             20.0  0.228100  ...   
Single-party rule                            40.0  0.130475  ...   
unknown                                      21.0  0.127619  ...   

                               regimenarrowcat          id              \
                                           75%   max count        mean   
Regime_type                                                              
Democracy                                  1.0   2.0  39.0   82.743590   
Military rule                              7.0   7.0  34.0   88.029412   
Monarchy                                   8.0   9.0  13.0   74.076923   
Multi-party authoritarian rule             5.0   5.0   6.0  118.000000   
Other oligarchy                           10.0  10.0   4.0  111.000000   
Personalist rule                           6.0   6.0  20.0   83.800000   
Single-party rule                          4.0   4.0  41.0   98.853659   
unknown                                   99.0  99.0  25.0  103.560000   

                                                                              
                                      std   min    25%    50%     75%    max  
Regime_type                                                                   
Democracy                       51.725855   7.0  43.00   76.0  114.00  171.0  
Military rule                   53.595842   3.0  35.75  102.5  139.50  159.0  
Monarchy                        38.953950   1.0  52.00   81.0  105.00  134.0  
Multi-party authoritarian rule  41.060930  58.0  97.50  120.0  138.75  175.0  
Other oligarchy                 69.928535  15.0  84.75  126.0  152.25  177.0  
Personalist rule                40.627447  25.0  48.25   91.0  113.50  173.0  
Single-party rule               57.112416   2.0  45.00  103.0  155.00  182.0  
unknown                         58.679269   4.0

In [52]:
df_grouped=df_Country.groupby('Regime_type')

In [54]:
df_grouped['Size.of.Government'].describe()

count      mean       std       min       25%  \
Regime_type                                                                     
Democracy                        39.0  6.451795  1.373909  3.770000  5.580000   
Military rule                    34.0  6.529087  1.194814  4.180000  5.789865   
Monarchy                         13.0  6.092708  1.133357  4.580000  5.150000   
Multi-party authoritarian rule    6.0  6.500642  0.950656  5.070000  6.044385   
Other oligarchy                   4.0  6.862838  0.482879  6.380000  6.537500   
Personalist rule                 20.0  6.253288  1.513037  2.020000  5.602500   
Single-party rule                41.0  4.968593  1.333538  2.378599  4.260000   
unknown                          25.0  6.050831  1.080706  3.360000  5.670000   

                                     50%       75%       max  
Regime_type                                                   
Democracy                       6.320000  7.495000  9.290000  
Military rule                   6.512366  7.530000  8.770000  
Monarchy                        6.041385  6.870000  8.556561  
Multi-party authoritarian rule  6.525000  7.031006  7.800000  
Other oligarchy                 6.800000  7.125338  7.471351  
Personalist rule                6.110693  7.483960  8.240000  
Single-party rule               5.071439  5.684556  8.102317  
unknown                         6.041385  6.249734  9.360000

In [55]:
df_Country.groupby('Regime_type')['Size.of.Government'].describe()

count      mean       std       min       25%  \
Regime_type                                                                     
Democracy                        39.0  6.451795  1.373909  3.770000  5.580000   
Military rule                    34.0  6.529087  1.194814  4.180000  5.789865   
Monarchy                         13.0  6.092708  1.133357  4.580000  5.150000   
Multi-party authoritarian rule    6.0  6.500642  0.950656  5.070000  6.044385   
Other oligarchy                   4.0  6.862838  0.482879  6.380000  6.537500   
Personalist rule                 20.0  6.253288  1.513037  2.020000  5.602500   
Single-party rule                41.0  4.968593  1.333538  2.378599  4.260000   
unknown                          25.0  6.050831  1.080706  3.360000  5.670000   

                                     50%       75%       max  
Regime_type                                                   
Democracy                       6.320000  7.495000  9.290000  
Military rule                   6.512366  7.530000  8.770000  
Monarchy                        6.041385  6.870000  8.556561  
Multi-party authoritarian rule  6.525000  7.031006  7.800000  
Other oligarchy                 6.800000  7.125338  7.471351  
Personalist rule                6.110693  7.483960  8.240000  
Single-party rule               5.071439  5.684556  8.102317  
unknown                         6.041385  6.249734  9.360000

In [62]:
df_Country['libdem_vdem_owid_nomiss'] = df_Country['libdem_vdem_owid'].fillna(df_Country['libdem_vdem_owid'].mean())

In [64]:
df_Country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 44 columns):
 #   Column                                                Non-Null Count  Dtype  
---  ------                                                --------------  -----  
 0   Entity                                                182 non-null    object 
 1   indiv_libs_vdem_owid                                  177 non-null    float64
 2   electdem_vdem_owid                                    177 non-null    float64
 3   libdem_vdem_owid                                      175 non-null    float64
 4   Countries                                             165 non-null    object 
 5   Economic.Freedom.Summary.Index                        182 non-null    float64
 6   Government.consumption                                182 non-null    float64
 7   Transfers.and.subsidies                               182 non-null    float64
 8   Government.investment                                 182 no

In [66]:
df_Country.iloc[3]['libdem_vdem_owid']

0.035

In [68]:
type(df_Country.iloc[3]['libdem_vdem_owid'])

numpy.float64

In [71]:
for i in range(0,182):
    if type(df_Country.iloc[3]['libdem_vdem_owid'])== str:
        print("string")

In [81]:
data = {'price': [100, 200, 150, 300]}
df = pd.DataFrame(data)
#apply lamda function to calculate discounted price
df['new_price'] = df['price'] * 0.9
df.head()

price  new_price
0    100       90.0
1    200      180.0
2    150      135.0
3    300      270.0

In [76]:
def transforming():
    if df['A'] >=3:
        return(x*2)
    else:
        return(x+5)

#function1 = lamdda x: x*2
#condition2 = df['A'] >= 3
#function2 = lambda x: x + 5
# Apply a function / Logic based on condition and create a new column
df['C'] = df ['B'].apply(lambda x: transforming x  #x* 2 if f['A'] < 3 else x: x + 5 ])

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (2239170940.py, line 5)

In [109]:
data = {'A': [1, 2, 3, 4, 5], 'B':[10, 20, 30, 40, 50]}
df = pd.DataFrame(data)
condition1 = df['A'] < 3
function1 = lambda x: x * 2
condition2 = df['A'] >= 3
function2 = lambda x: x + 5

#Apply the funct / logic based on cond and create the new column
df['C'] = np.where(condition1, function1(df['A']), function2(df['B']))

print(df)


   A   B   C
0  1  10   2
1  2  20   4
2  3  30  35
3  4  40  45
4  5  50  55


In [98]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (3, 2))
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [100]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (2, 3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [102]:
# Transpose an array
arr = np.array([[1, 2, 3], [4, 5, 6]])

transposed_arr = np.transpose(arr)
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [105]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
transposed_arr = np.transpose(arr)
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [106]:
# Split an array into sub-arrays
arr = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.split(arr, 3)
print(sub_arrays)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [107]:
# Resize an array
arr = np.array([1, 2, 3])
resized_arr = np.resize(arr, (2, 5))
print(resized_arr)


[[1 2 3 1 2]
 [3 1 2 3 1]]
